name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.

          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible

            - [x] Create an issue for making any changes to code. When the issue is approved you can make changes.
            - [x] Pull latest change from upstream branch before starting the changing of code.
            - [x] Add your file in a properly named directory (lowercase) 
            - [x] Use Flake8 locally for linting Python Code. (We have linting checks so if your code fails it we will not merge the PR.)
              - `pip install flake8`
            - [x] Add pytest/unittest if possible
            - [x] Add README.md for your script instructions to run the script with required dependencies.
            - [x] Script should be in plugin format. (if possible, it will be great
